### ISSUE TITLE
Pflichtenheft - Übersicht

### ISSUE THREAD

**Issue by vlle1** [vlle1/dokumente-earablesKIT#2]
generell: 
- 20 Seiten

Checkliste und Struktur:
- [ ] #4 Einleitung: Vollst. Beschreibung der Aufgabenstellung. 
- [ ] #5 Zielbestimmungen: Essentiell. Beschreibt die Funktionalität des Systems. 
Musskriterien: Mindestanforderungen, gehen aus Aufgabenstellung hervor.
Wunschkriterien: Von euch selbst definierte, zusätzliche Funktionalität.
Abgrenzungskriterien: Selbsterklärend. 
- [ ] #6 Produkteinsatz: Beschreibt Einsatzgebiet, Zielgruppe und Betriebsbedingungen. 
- [x] #7 Produktumgebung: Notwendige Hard- und Software. 
- [x] #8 Produktfunktionen: Essentiell. Detailliertere Beschreibung der Funktionalität, wiederum gegliedert in Grundfunktionen und optionale Funktionen. 
- [x] #9 Produktdaten: Anfallende Daten außerhalb des Quellcodes. 
- [ ] #10 (von uns) nichtfunktionale Anforderungen (Produktleistungen: Anforderungen an Laufzeitverhalten oder Speicherplatz. Wichtig z.B. bei Echtzeitsystemen, eingebetteten Systemen, Qualitätszielbestimmungen: Anforderungen an Stabilität des Systems. 
)
- [ ] #11 Bedienoberfläche: Essentiell. Screenshots der angedachten Bedienoberfläche (z.B. Prototyp oder frei gezeichnet) und Erläuterung der Menüstruktur. 
- [ ] #12 Testfälle und Testszenarien: Essentiell. Testfälle für die einzelnen Produktfunktionen, die alle abgedeckt sein müssen. Testszenarien für typische Anwendungsszenarien. 
- [ ] #14 Systemmodell: Essentiell. Grobes Architekturdiagramm plus Beschreibung. 
- [x] #13 Entwicklungsumgebung: Zur Entwicklung verwendete Hard- und Software. In der Pflichtenheft-Phase sollt ihr euch in diese Tools einarbeiten und vorläufig festlegen. 
- [ ] Glossar

**Comment by vlle1** [comment]
Issues schließen, wenn es im groben passt und alle Unklarheiten als Kommentare im Code.
